site_name: DMCC

pages:
- Home: index.md
- About: about.md
- People: people.md
- Publications: publications.md
- Projects: 
    - Sternberg: sternberg.md
    - AXCPT: axcpt.md
    - Stroop: stroop.md
    - Task Switching: task_switching.md
- Tasks:
    - About: tasks.md
    - Download: task_downloads.md
- Analysis:
    - R Code Downloads: rcode.md
    - Interactive: interactive.md


markdown_extensions:
    - toc:
        permalink: True